export const redocThemeOptions = {    
       theme:{
         codeBlock:{
           backgroundColor:"#11171a",
         },
         colors:{
           responses:{
             error:{
               tabTextColor:"#1b1b29"
             },
             info:{
               tabTextColor:"#1b1b29",
             },
             success:{
               tabTextColor:"#0c0b1a"
             },
           },
           text:{
             primary:"#1b1b29",
             secondary:"#4d4d4d"
           }
         },
         rightPanel:{
           backgroundColor:"#253237",
         },
         sidebar:{
           backgroundColor:"#ffffff"
         },
         typography:{
           code:{
             color:"#0c0b1a"
           }
         }
       }
     }