brews:
  -
    name: kubeshark
    homepage: https://github.com/kubeshark/kubeshark
    tap:
      owner: kubeshark
      name: homebrew-kubeshark
    commit_author:
      name: atileren
      email: atil.eren@outlook.com