apiVersion: v2
name: kubeshark
version: "52.11.7"
description: The API Traffic Analyzer for Kubernetes
home: https://www.kubehq.com
keywords:
  - kubeshark
  - packet capture
  - traffic capture
  - traffic analyzer
  - network sniffer
  - observability
  - devops
  - microservice
  - forensics
  - api
kubeVersion: '>= 1.16.0-0'
maintainers:
  - email: info@kubehq.com
    name: Kubeshark
    url: https://www.kubehq.com
sources:
  - https://github.com/kubeshark/kubeshark/tree/master/helm-chart
type: application
icon: https://raw.githubusercontent.com/kubeshark/assets/master/logo/vector/logo.svg
