kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.volumeClaim.name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 700M
    requests:
      storage: 700M
