---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    kubeshark-cli-version: v1
    kubeshark-created-by: kubeshark
    kubeshark-managed-by: kubeshark
  name: kubeshark-cluster-role
  namespace: kubeshark
rules:
  - apiGroups:
      - ""
      - extensions
      - apps
      - networking.k8s.io
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - ingresses
    verbs:
      - list
      - get
      - watch
