# This example shows permissions that enrich the logs with additional info in namespace-restricted mode
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeshark-runner-debug-role
rules:
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeshark-runner-debug-rolebindings
subjects:
- kind: User
  name: user-with-restricted-access
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: kubeshark-runner-debug-role
  apiGroup: rbac.authorization.k8s.io
