---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    kubeshark-created-by: kubeshark
    kubeshark-managed-by: kubeshark
  name: '{{ .Values.tap.selfnamespace }}'
spec: {}
status: {}
