---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  {{- include "kubeshark.labels" . | nindent 4 }}
  {{- if .Values.tap.serviceaccount.labels }}
    {{- toYaml .Values.tap.serviceaccount.labels | nindent 4 }}
  {{- end }}
  annotations:
  {{- if .Values.tap.annotations }}
    {{- toYaml .Values.tap.annotations | nindent 4 }}
  {{- end }}
  {{- if .Values.tap.serviceaccount.annotations }}
    {{- toYaml .Values.tap.serviceaccount.annotations | nindent 4 }}
  {{- end }}
  name: {{ include "kubeshark.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
