---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "kubeshark.labels" . | nindent 4 }}
  {{- if .Values.tap.annotations }}
  annotations:
    {{- toYaml .Values.tap.annotations | nindent 4 }}
  {{- end }}
  name: {{ include "kubeshark.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.tap.docker.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.tap.docker.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
{{- end }}
