---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubeshark.com/app: hub
    {{- include "kubeshark.labels" . | nindent 4 }}
  {{- if .Values.tap.annotations }}
  annotations:
    {{- toYaml .Values.tap.annotations | nindent 4 }}
  {{- end }}
  name: kubeshark-hub
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: kubeshark-hub
      port: 80
      targetPort: 8080
  selector:
    app.kubeshark.com/app: hub
  type: ClusterIP
