---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: kubeshark-front
    kubeshark-created-by: kubeshark
    kubeshark-managed-by: kubeshark
  name: kubeshark-front
  namespace: '{{ .Values.tap.selfnamespace }}'
spec:
  containers:
    - env:
        - name: REACT_APP_DEFAULT_FILTER
          value: ' '
        - name: REACT_APP_HUB_HOST
          value: ' '
        - name: REACT_APP_HUB_PORT
          value: '{{ .Values.tap.ingress.enabled | ternary "80/api" "8898" }}'
      image: '{{ .Values.tap.docker.registry }}/front:{{ .Values.tap.docker.tag }}'
      imagePullPolicy: '{{ .Values.tap.docker.imagepullpolicy }}'
      name: kubeshark-front
      ports:
        - containerPort: 80
          hostPort: {{ .Values.tap.proxy.front.srvport }}
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 1
        successThreshold: 1
        tcpSocket:
          port: 80
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 750m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 50Mi
  dnsPolicy: ClusterFirstWithHostNet
  serviceAccountName: kubeshark-service-account
  terminationGracePeriodSeconds: 0
  tolerations:
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists
status: {}
