---
{{- if .Values.tap.snapshots.local.storageClass }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "kubeshark.labels" . | nindent 4 }}
  {{- if .Values.tap.annotations }}
  annotations:
    {{- toYaml .Values.tap.annotations | nindent 4 }}
  {{- end }}
  name: {{ include "kubeshark.name" . }}-snapshots-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tap.snapshots.local.storageSize }}
  storageClassName: {{ .Values.tap.snapshots.local.storageClass }}
status: {}
{{- end }}
