{{ if and .Values.kmm.enabled  (.Capabilities.APIVersions.Has "kmm.sigs.x-k8s.io/v1beta1") }}
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: kubeshark-module-loader
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: pf_ring
        dirName: /opt
      imagePullPolicy: Always
      kernelMappings:
        - regexp: '^.+$'
          containerImage: "kubeshark/module-loader:latest"
          build:
            dockerfileConfigMap:
              name: kubeshark-module-loader-dockerfile
          sign:
            certSecret:
              name: cert-secret
            keySecret:
              name: key-secret
            filesToSign:
              - /opt/lib/modules/5.10.0-23-amd64/pf_ring.ko
  selector:
    beta.kubernetes.io/arch: amd64
{{- end }}
