---
kind: Service
apiVersion: v1
metadata:
  name: kubeshark-worker-metrics
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '{{ .Values.prometheus.service.port }}'
spec:
  selector:
    app.kubeshark.co/app: worker
    {{- include "kubeshark.labels" . | nindent 4 }}
  ports:
  - name: metrics
    protocol: TCP
    port: {{ .Values.prometheus.service.port }}
    targetPort: {{ .Values.prometheus.service.port }}