{{ if .Values.tap.gitops.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: kubeshark-cleanup-job
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "kubeshark.serviceAccountName" . }}
      {{- if .Values.tap.priorityClass }}
      priorityClassName: {{ .Values.tap.priorityClass | quote }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: cleanup
        {{- if .Values.tap.docker.overrideImage.hub }}
          image: '{{ .Values.tap.docker.overrideImage.hub }}'
        {{- else if .Values.tap.docker.overrideTag.hub }}
          image: '{{ .Values.tap.docker.registry }}/hub:{{ .Values.tap.docker.overrideTag.hub }}'
        {{ else }}
          image: '{{ .Values.tap.docker.registry }}/hub:{{ not (eq .Values.tap.docker.tag "") | ternary .Values.tap.docker.tag (include "kubeshark.defaultVersion" .) }}'
        {{- end }}
          command: ["/app/cleanup"]
{{ end -}}
