{{- if .Values.tap.auth.dexConfig }}

kind: Secret
apiVersion: v1
metadata:
  name: kubeshark-dex-conf-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubeshark.com/app: hub
    {{- include "kubeshark.labels" . | nindent 4 }}
data:
  dex-config.yaml: {{ .Values.tap.auth.dexConfig | toYaml | b64enc | quote }}

{{- end }}
