{{- if .Values.tap.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "kubeshark.labels" . | nindent 4 }}
  {{- with .Values.tap.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tap.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: kubeshark-metrics
  namespace: {{ .Release.Namespace }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubeshark.com/metrics: "true"
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: metrics
      {{- with .Values.tap.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.tap.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.tap.metrics.serviceMonitor.path }}
      path: {{ . }}
      {{- end }}
      {{- with .Values.tap.metrics.serviceMonitor.scheme }}
      scheme: {{ . }}
      {{- end }}
      {{- if .Values.tap.metrics.serviceMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
      {{- with .Values.tap.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tap.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
