kind: Secret
apiVersion: v1
metadata:
  name: kubeshark-hub-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubeshark.co/app: hub
    {{- include "kubeshark.labels" . | nindent 4 }}
stringData:
    LICENSE: '{{ .Values.license }}'
