on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Linter

permissions:
  contents: read

jobs:
  golint:
    name: Golint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Go lint - agent
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: agent
          args: --timeout=10m

      - name: Go lint - shared
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: shared
          args: --timeout=10m

      - name: Go lint - CLI
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: cli
          args: --timeout=10m

      - name: Go lint - logger
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          working-directory: logger
