on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Linter

permissions:
  contents: read

jobs:
  golint:
    name: Golint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Go lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=10m
