name: system tests
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'develop'
jobs:
  run-system-tests:
    name: Run system tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - shell: bash
        run: |
          source ./test-installations.sh

      - name: Test
        run: make system-test
