name: Validations
on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]
jobs:
  setup:
    name: setup golang and pull go
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

  build-cli:
    needs: setup
    name: Build CLI
    runs-on: ubuntu-latest
    steps:
      - name: Build CLI
        run: make cli

  build-agent:
    needs: setup
    name: Build Agent
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          sudo apt-get install libpcap-dev

      - name: Build Agent
        run: make agent

  run-tests-cli:
    needs: setup
    name: Run CLI tests
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: make test-cli

  run-tests-agent:
    needs: setup
    name: Run Agent tests
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          sudo apt-get install libpcap-dev

      - name: Test
        run: make test-agent

  publis-to-codecov:
    needs:
      - run-tests-agent
      - run-tests-cli
    name: Publish to codecov
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

