name: Validation
on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
  push:
    branches:
      - 'develop'
      - 'main'
jobs:
  build-cli:
    name: Build CLI
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build CLI
        run: make cli

  build-agent:
    name: Build Agent
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - shell: bash
        run: |
          sudo apt-get install libpcap-dev

      - name: Build Agent
        run: make agent

  run-tests:
    name: Build Agent
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
